---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: src/content/projects
  label: Projects
  create: all
  match: "**/*"
  templates:
  - project
- type: document
  path: src/content/about.md
  label: About
upload_dir: static/assets/media
public_path: "/media"
front_matter_path: "/media"
use_front_matter_path: true
file_template: ":filename:"
instant_preview: 
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  instant_preview_command: gatsby develop -H 0.0.0.0 -p 8080
  preview_command: gatsby build
