---
label: Project
hide_body: true
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- type: text
  name: template
  label: Template
  hidden: true
  default: project
- name: date
  label: Date
  type: datetime
  hidden: true
  default: ''
- type: textarea
  default: ''
  label: Description
  name: description
- type: file
  name: thumbnail
  label: Thumbnail
  config:
    maxSize: '12'
- name: gallery_images
  label: Gallery images
  type: image_gallery
  hidden: false
  default: ''
pages:
- src/content/projects/test.md
