on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: npm install, build and test
      run: |
        npm install
        npm run build --if-present
        npm test
    - name: Test
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ftp.faith.ca
        FTP_USERNAME: faith.ca
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        REMOTE_DIR: testftp
        LOCAL_DIR: public
#         ARGS: --delete
        # --delete arg will delete files on the server if you've deleted them in git
